{
  "formatVersion": "1.1",
  "component": {
    "group": "com.custom.plugin",
    "module": "arouter-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.custom.plugin",
          "module": "arouter-annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "arouter-api-1.0.1.aar",
          "url": "arouter-api-1.0.1.aar",
          "size": 61848,
          "sha512": "52920f241959e8f87ba981b28843b58cac2975f6dec1aa5bf309769a1ba3e745b740192b3dd0c90000adf0b70a53f3f7f44f81fb2aba39a6701773e45385e19c",
          "sha256": "faddf30cad616e460954752642520d1510352e0cf93d41e7458ac5e5a056f864",
          "sha1": "37b6f9d089b833348e61adacda7219a92b730269",
          "md5": "baa6f8fd4b66a13d059b35bb0710da29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.custom.plugin",
          "module": "arouter-annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "arouter-api-1.0.1.aar",
          "url": "arouter-api-1.0.1.aar",
          "size": 61848,
          "sha512": "52920f241959e8f87ba981b28843b58cac2975f6dec1aa5bf309769a1ba3e745b740192b3dd0c90000adf0b70a53f3f7f44f81fb2aba39a6701773e45385e19c",
          "sha256": "faddf30cad616e460954752642520d1510352e0cf93d41e7458ac5e5a056f864",
          "sha1": "37b6f9d089b833348e61adacda7219a92b730269",
          "md5": "baa6f8fd4b66a13d059b35bb0710da29"
        }
      ]
    }
  ]
}
